### ISSUE TITLE
Throw `DomainError` with custom error message for each parameter inside constructor.

### ISSUE THREAD

**Issue by MonssafToukal** [farhadrclass/KnetNLPModelsProblems.jl#22]
https://github.com/farhadrclass/KnetNLPModelsProblems.jl/blob/65a606f26e578702b7e3a3a0ebf3eb9fb98acce0/src/solver_pram.jl#L33-L42

Maybe we can do something like this:

`throw(DomainError("value $(new_value) should be in domain"))`

**Comment by farhadrclass** [comment]
thanks , I updated the code
