### ISSUE TITLE
Use kargs... in parameter constructor

### ISSUE THREAD

**Issue by tmigot** [farhadrclass/KnetNLPModelsProblems.jl#24]
Something like
```
function R2ParameterSet(; atol = 1e-7, rtol = 1e-5, η1 = 1., η2 = 2., γ1 = 3., γ2 = 4., σmin = 5., β = 6.)
```
So that you would only need one constructor instead of two.

https://github.com/farhadrclass/KnetNLPModelsProblems.jl/blob/1f818f9fdcec8c46a130be8437c7d294bc495515/src/JSOSolver_SR2.jl#L31

**Comment by farhadrclass** [comment]
I updated the code

**Comment by tmigot** [comment]
Looks great, thanks
